version: "3"
services:
  react:
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "8085:80"
  server:
    image: node:16.14.0
    working_dir: /app/server
    volumes:
      - ./server:/app/server
    command: npm start
    environment:
      MONGO_URI: mongodb://mongo:27017/donations
      STRIPE_SK: ${STRIPE_SK}
      ENDPOINT_SECRET: ${STRIPE_WHSEC}
    ports:
      - "8086:3006"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
